"""Shared models for the Cyton host application."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

import numpy as np
from numpy.typing import NDArray


FloatArray = NDArray[np.float64]


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


@dataclass(frozen=True)
class StreamFrame:
    """One host-side batch of EEG samples."""

    samples: FloatArray
    timestamps: FloatArray
    channel_names: tuple[str, ...]
    sampling_rate: float

    @property
    def n_samples(self) -> int:
        return int(self.samples.shape[1]) if self.samples.ndim == 2 else 0


@dataclass(frozen=True)
class HostEvent:
    """A control or calibration event generated by the host."""

    event_type: str
    message: str
    created_at: str = field(default_factory=utc_now_iso)
    payload: dict[str, Any] = field(default_factory=dict)
